# Spring Configuration
spring:
  application:
    name: Wallet Data
  main:
    web-application-type: reactive

# Server Configuration
server:
  port: 8080

# Logging configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    # Set the log level for the entire application
    root: INFO
    # Set log level for specific packages or classes
    es.in2.wallet.data.api.service: DEBUG
    es.in2.wallet.data.api.util: DEBUG

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      enabled: true
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /spring-ui
    tags-sorter: alpha
    operations-sorter: method

openapi:
  server:
    url:
    description:
  info:
    title:
    version:
    termsOfService:
    license:
      name:
      url:
    contact:
      email:
      name:
      url:
    description:

broker:
  domain:
  url:

wallet-crypto:
  domain:
  url:

wallet-wda:
  domain: